version: '3'
services:
  med-web-helper-wui:
    build:
      context: .
      dockerfile: docker/Dockerfile.wui
    ports:
     - "80:80"
    depends_on:
     - med-web-helper-redis
     - med-web-helper-mysql
#     - med-web-helper-preproc
    networks:
     - med-web-helper
    volumes:
     - "./data/wui/log:/docato_data/log"
     - "./data/wui/media:/docato_data/media"
    restart: unless-stopped

#  med-web-helper-preproc:
#    build:
#      context: .
#      dockerfile: dockerfiles/Dockerfile.preproc
#    depends_on:
#     - med-web-helper-mysql
#     - med-web-helper-redis
#    networks:
#     - med-web-helper
#    restart: unless-stopped

  med-web-helper-redis:
    image: redis
    networks:
      med-web-helper:
        aliases:
         - med-web-helper-redis
    restart: unless-stopped

  med-web-helper-mysql:
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: med_web_helper
    volumes:
     - ./data/mysql:/var/lib/mysql
    image: mysql:5.5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --max-allowed-packet=104857600
    networks:
      med-web-helper:
        aliases:
         - med-web-helper-mysql
    restart: unless-stopped

networks:
  med-web-helper:
