version: '3'
services:
  wui:
    image: pavlovma007/docato-wui-20200312
    ports:
     - "80:80"
    depends_on:
     - rabbit
     - mysql
    networks:
     - docato
    volumes:
     - "/home/mp/SATEK/docato_data/log:/docato_data/log"
     - "/home/mp/SATEK/docato_data/media:/docato_data/media"
    restart: unless-stopped

  preproc:
    image: pavlovma007/docato-preproc-20200312
    depends_on:
     - mysql
     - rabbit
    links:
     - rabbit
    networks:
     - docato
    volumes:
     - "/home/mp/SATEK/docato_data/log:/docato_data/log"
     - "/home/mp/SATEK/docato_data/media:/docato_data/media"
     - "/var/run/docker.sock:/var/run/docker.sock"


  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=mypass
      networks:
        - docato
      ports:
          - "5673:5672"

  mysql:
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: docato
    volumes:
     #- /home/mp/SATEK/docato/mysql:/var/lib/mysql
     - /home/mp/SATEK/docato_data/mysql_fromdevyatkin2:/var/lib/mysql
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --max-allowed-packet=500M --innodb_log_file_size=10000000000
    networks:
      docato:
        aliases:
         - mysql
    restart: unless-stopped

networks:
  docato:
