version: '3'
services:
  wui:
    image: windj007/docato-wui
    ports:
     - "80:80"
    depends_on:
     - redis
     - mysql
    networks:
     - docato
    volumes:
     - "/home/mp/SATEK/docato/log:/docato_data/log"
     - "/home/mp/SATEK/docato/media:/docato_data/media"
    restart: unless-stopped

  preproc:
    image: windj007/docato-preproc
    depends_on:
     - mysql
     - rabit
    links:
     - rabit
    networks:
     - docato
    volumes:
     - "/home/mp/SATEK/docato/log:/docato_data/log"
     - "/home/mp/SATEK/docato/media:/docato_data/media"
    restart: unless-stopped

  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=admin
          - RABBITMQ_DEFAULT_PASS=mypass
      networks:
        - docato
      ports:
          - "5673:5672"

  mysql:
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: docato
    volumes:
     #- /home/mp/SATEK/docato/mysql:/var/lib/mysql
     - /home/mp/SATEK/docato/mysql_fromdevyatkin2:/var/lib/mysql
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --max-allowed-packet=500M --innodb_log_file_size=10000000000
    networks:
      docato:
        aliases:
         - mysql
    restart: unless-stopped

networks:
  docato:
