version: '3'
services:
  wui:
    image: windj007/docato-wui
    ports:
     - "80:80"
    depends_on:
     - redis
     - mysql
#     - preproc
    networks:
     - docato
    volumes:
     - "/home/windj/projects/med_web_helper/new_data/wui/log:/docato_data/log"
     - "/home/windj/projects/med_web_helper/new_data/wui/media:/docato_data/media"
    restart: unless-stopped

  preproc:
    image: windj007/docato-preproc
    depends_on:
     - mysql
     - redis
    networks:
     - docato
    volumes:
     - "/home/windj/projects/med_web_helper/new_data/wui/log:/docato_data/log"
     - "/home/windj/projects/med_web_helper/new_data/wui/media:/docato_data/media"
    restart: unless-stopped

  redis:
    image: redis
    networks:
      docato:
        aliases:
         - redis
    restart: unless-stopped

  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: docato
    volumes:
     - /home/windj/projects/med_web_helper/new_data/mysql:/var/lib/mysql
    image: mysql:5.5
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --max-allowed-packet=104857600
    networks:
      docato:
        aliases:
         - mysql
    restart: unless-stopped

networks:
  docato:
